baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Ady Mehta
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 1 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 4

params:
    description: "I'm a student at Berkeley and I like learning math, economics, finance, cognition, and computation. I hope to apply these toward building cool products, writing effective algorithms, and researching human decision-making."
    author: Ady Mehta
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ady Mehta
          subtitle: "I'm a student at Berkeley and I like learning math, economics, finance, cognition, and computation. I hope to apply these toward building cool products, writing effective algorithms, and researching human decision-making."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Moritz-Maria von Igelfeld
          buttons:
            - name: Book Reviews
              url: books/
            - name: Paper Summaries
              url: papers/
            - name: Courses
              url: courses/
            - name: Projects
              url: data/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: Email
          url: ady.s.miti@gmail.com
        - name: CV
          url: cv.pdf
        - name: Office Hours
          url: officehours/
        - name: GitHub
          url: https://github.com/pmichaillat
        - name: YouTube
          url: https://www.youtube.com/@alexandermccallsmithoffici9000

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ady Mehta"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
